name: Conventional Commits Validation

on:
  push:
    branches:
      - 'features/*'
      - 'hotfix/*'

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Validate commits
        run: npx commitlint --from=${{ github.event.before }} --to=${{ github.sha }}
